# Generated by Django 2.2.6 on 2019-11-06 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_dst_port', models.CharField(max_length=200, unique=True)),
                ('application_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataBaseLifetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lifetime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceconfigDir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Devicedb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999, unique=True)),
                ('ip', models.GenericIPAddressField(default='1.1.1.1', unique=True)),
                ('description', models.TextField(blank=True)),
                ('snmp_enable', models.BooleanField(default=False)),
                ('snmp_ro_community', models.CharField(max_length=999)),
                ('snmp_rw_community', models.CharField(blank=True, max_length=999)),
                ('ssh_username', models.CharField(max_length=999)),
                ('ssh_password', models.CharField(max_length=999)),
                ('enable_password', models.CharField(blank=True, max_length=999)),
                ('change_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(blank=True, max_length=999, null=True)),
                ('record_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='devnet2019.Devicedb')),
            ],
        ),
        migrations.CreateModel(
            name='Devicetype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
                ('change_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldTypeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField(unique=True)),
                ('field_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitorInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Smtplogindb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailserver', models.CharField(blank=True, max_length=999, null=True)),
                ('mailusername', models.CharField(blank=True, max_length=999, null=True)),
                ('mailpassword', models.CharField(blank=True, max_length=999, null=True)),
                ('mailfrom', models.CharField(blank=True, max_length=999, null=True)),
                ('mailto', models.CharField(blank=True, max_length=999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SNMPtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snmp_type', models.CharField(max_length=100, unique=True)),
                ('snmp_name', models.CharField(max_length=100, null=True)),
                ('change_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thresholdcpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_threshold', models.IntegerField(blank=True, default=0, null=True)),
                ('alarm_interval', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thresholdmem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_threshold', models.IntegerField(blank=True, default=0, null=True)),
                ('alarm_interval', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thresholdutilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilization_threshold', models.IntegerField(blank=True, default=0, null=True)),
                ('alarm_interval', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sidebar', to='devnet2019.Navbar')),
            ],
        ),
        migrations.CreateModel(
            name='NetflowClassicSeven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4_src_addr', models.GenericIPAddressField(protocol='IPv4')),
                ('ipv4_dst_addr', models.GenericIPAddressField(protocol='IPv4')),
                ('protocol_id', models.IntegerField()),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('input_interface_id', models.IntegerField()),
                ('in_bytes', models.BigIntegerField()),
                ('record_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netflow_app', to='devnet2019.ApplicationMap')),
            ],
        ),
        migrations.CreateModel(
            name='LastAlarmUtilization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_alarm_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('interface', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilization_last_alarm', to='devnet2019.DeviceInterface')),
            ],
        ),
        migrations.CreateModel(
            name='LastAlarmMEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_alarm_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem_last_alarm', to='devnet2019.Devicedb')),
            ],
        ),
        migrations.CreateModel(
            name='LastAlarmCPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_alarm_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_last_alarm', to='devnet2019.Devicedb')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSNMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.CharField(max_length=999, null=True)),
                ('change_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devicesnmp', to='devnet2019.Devicetype')),
                ('snmp_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devicesnmp', to='devnet2019.SNMPtype')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReachable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snmp_reachable', models.BooleanField(default=False)),
                ('ssh_reachable', models.BooleanField(default=False)),
                ('record_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reachable', to='devnet2019.Devicedb')),
            ],
        ),
        migrations.CreateModel(
            name='Devicemem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_usage', models.FloatField(blank=True, default=0)),
                ('record_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mem_usage', to='devnet2019.Devicedb')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInterfaceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('record_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_state', to='devnet2019.DeviceInterface')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInterfaceSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.BigIntegerField(blank=True, default=0, null=True)),
                ('record_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('interface', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_speed', to='devnet2019.DeviceInterface')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInterfaceOutBytes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_bytes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('record_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_out_bytes', to='devnet2019.DeviceInterface')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInterfaceInBytes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_bytes', models.BigIntegerField(blank=True, default=0, null=True)),
                ('record_datetime', models.DateTimeField(auto_now=True, null=True)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interface_in_bytes', to='devnet2019.DeviceInterface')),
            ],
        ),
        migrations.AddField(
            model_name='devicedb',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device', to='devnet2019.Devicetype'),
        ),
        migrations.CreateModel(
            name='Devicecpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(blank=True, default=0)),
                ('record_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cpu_usage', to='devnet2019.Devicedb')),
            ],
        ),
        migrations.CreateModel(
            name='Deviceconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=200)),
                ('config_filename', models.CharField(max_length=200)),
                ('backup_datetime', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='devnet2019.Devicedb')),
            ],
        ),
        migrations.CreateModel(
            name='DepartTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departtitle', to='devnet2019.Department')),
            ],
        ),
    ]
